Add Unit Tests to check obfuscation of PII Data
aws/porting-assistant-dotnet-ui pull request #80
Opened 2021-08-17 16:39 UTC by aniruddhadave

*Description of changes:*
- Add Unit Tests to check obfuscation of PII Data

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including READMEs and comments (where appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific environment

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-17 17:25 UTC, flywanli commented on packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PIIObfuscationUnitTest.cs
> +        [TestMethod]
could you use nunit to write unit test

2021-08-23 20:23 UTC, kanikaul-amazon requested changes
Hey thanks for adding this. Left a few minor comments

2021-08-23 20:23 UTC, kanikaul-amazon commented on packages/csharp/PortingAssistant/PortingAssistant.UnitTests/PIIObfuscationUnitTest.cs
> +            var encryptedSolutionPath = Crypto.SHA256(solutionPath); // 462eb7f46af82bd5155ef9f28ca3f5f638f702a7423b105478fa3d9267a344da
Do we need this comment?

2021-08-23 20:23 UTC, kanikaul-amazon commented on packages/csharp/PortingAssistant/PortingAssistant.Common/Utils/TelemetryCollectionUtils.cs
> +        public static void CollectNugetMetrics(Task<PackageAnalysisResult> result, AnalyzeSolutionRequest request, string tgtFramework)
nit: rename to packageAnalysisResult for consistency

2021-08-23 20:36 UTC, kanikaul-amazon approved these changes

2021-08-23 21:05 UTC, merged